### ISSUE TITLE
Session hotfixes @ Lille 15/10/2022

### ISSUE THREAD

**Issue by moussor** [samuelhackwill/SRT_OTLPUFRALR#1]
Samedi 15/10/2022 @ Lille
- pb avec le rasp :
    - pas de connectivité internet (chez Makewaves et chez Stéphanie)
        - —> chez Samuel, l’IP était statique auparavant du coup Samuel a changé la config pour obtenir une ip dynamique en DHCP, et le rasp se connectait bien à l’internet mondial, mais toujours erreur de GStreamer
        - —> chez Makewaves, pas d’internet, on a changé les serveurs dns dans /etc/network/interfaces (pour mettre ceux de Google 8.8.8.8…) mais ça n’a pas fonctionné
        - —> on a changé la date et l’heure manuellement (qui était à 1970) et activé le NTP mais le rasp ne semble pas faire de synchronisation quand même
- pb avec Janus
    - le script start-janus.sh renvoie une erreur concernant DTLS et des clés (janus_dtls_load_keys : Error opening certificate file)
    - janus n’est pas lancé sur le port 8088 —> [ontraverseralepont.com/janus](http://ontraverseralepont.com/janus) : nginx renvoie une erreur 502 car l’application (janus) n’est pas lancée (nous supposons)

**Comment by samuelhackwill** [comment]
a priori le tunnel SSH fonctionne chez moi (et j'arrive à ping tout le monde sur internet) donc les problèmes réseau du rasp seraient plutôt liés à la connection à Lille.

**Comment by samuelhackwill** [comment]
Guillaume, 18/10 : 

Ce que j'ai fait :
 - MAJ de tout le serveur (sécu, etc)
 - Installation de la dernière version de JANUS (ça va grandement améliorer les choses)
 - Configuration de JANUS pour ne pas écouter sur l'ipv6
 - Changement du fichier sur le raspberry pour être en mono avec cette carte son

**Comment by samuelhackwill** [comment]
all systems are go!

**Comment by moussor** [comment]
top! bravo et merci  @samuelhackwill @glibersat
